### PR TITLE
add biquad_bank.rs as base for filter banks

### PR DESCRIPTION
**Pull request by rhizoome**
### Why

This is a prototype. As I am somebody who can tinker on things forever. I want to get it out early. This does not mean I want it to be committed like that.

I am building a vocoder like thing with formant/pitch-shift. Therefore I need a ton of resonators and I want them to be as fast as possible.

### What

I implemented the trait `Realx` based on `Num` as an analog to `Real`. It is intended to work with f32x8 and f64x4. I first wanted to drop f64x4, but then I heard from @SamiPerttu that they are going to (re)introduce 64-bit to simd. Then I took `BiquadCoefs` and removed everything but `resonator()`. I slightly changed the calculations. I introduced the generic parameter `Size` to `BiquadBank` and used it for `type Outputs` and for some strange reason not for `type Inputs`, but I need to change this.

### TODO

- [ ] I need to investigate how things are tested in funDSP.
- [x] Implement `Size` for `type Inputs`
- [x] Get `fn set()` to work (EDIT: like below)
- [ ] Get `fn route()` and `fn response()` to work

### Performance

```shell
ganwell•~/Repos/fundsp_player(main)» /usr/bin/time target/release/player bank_simd dummy --seconds 400
        0.39 real         0.38 user         0.00 sys
ganwell•~/Repos/fundsp_player(main)» /usr/bin/time target/release/player bank_current dummy --seconds 400
        1.12 real         1.11 user         0.00 sys
```

Based on [this code](https://github.com/rhizoome/fundsp_player/blob/ea7ccfd656c482afb7e22d374bd8498dd994f6a7/src/build.rs#L32) run on an Apple M1.

### Assumptions

- I think `BiquadBank` should take N inputs and N outputs, since this is the generic part. Usually resonator-banks use one input and one output. Strangely the current implementation takes 1 input and N outputs, just for reasons. I am going to change that, but I wanted to get something out early.
- I used `sample_rate: f32` on `fn resonator()` without checking if that is compliant with the rest of `fundsp`.
- I assumed that implementing `fn set()` properly would be complicated since we would introduce generic-parameters on `Settings`, but maybe there is a nice trick to avoid that.
- There are probably more (incorrect) assumption I made, please let me know.

### Questions

- `fn response()` and `fn route()` confuse me. How do I build that for multiple channels? I guess the confusion stems from not understanding the purpose of either. Given enough time passes, I'll investigate and understand it. But any hints are welcome.
- If those who review this see mistakes I did in [fundsp_player](https://github.com/rhizoome/fundsp_player), let me know. I tried to use block processing, to get best performance. I already changed to typnum-type to U8, but above I linked to exact version I did the performance test with.

### Plans

Of course if my idea of biquad_bank.rs does not fit funDSP that is absolutely fine. If possible I like to merge some correct, but minimal version of biquad_bank.rs and build from there. But I am also okey with leaving this PR open till there is a respectable amount of filter-banks.

### CODE REVIEW

**Comment by rhizoome** [comment]
> I assumed that implementing fn set() properly would be complicated since we would introduce generic-parameters on Settings, but maybe there is a nice trick to avoid that.

Maybe we could use the signature:

```rust
    /// Set biquad-bank parameters `(index, a1, a2, b0, b1, b2)`.
    BiquadBank(usize, f32, f32, f32, f32, f32),
```

So to set the complete bank, one would need to set BiquadBank(0... to  BiquadBank(7... for f32x8 or BiquadBank(0... to  BiquadBank(3... for f64x4.

**Comment by rhizoome** [comment]
### Performance

Only 10% of time is spent in biquad. That means my test does not actually mean that SIMD is faster. It means that calculating  filter-bank is faster. The performance gain would be similar if we just used [f32; 8]. I am not sure what that means yet.

image

**Comment by SamiPerttu** [comment]
Thanks for the PR! I'll merge it after I get 0.19 released, then we can iterate on it.

**Comment by rhizoome** [comment]
I [implemented settings (Paarameter::BiquadBank) for BiquadBank](https://github.com/SamiPerttu/fundsp/pull/51/commits/e2b195c8a5a98057c4d85744925e59fd8e146030) and rebased on masten.

**Comment by rhizoome** [comment]
I [changed BiquadBank to have Size (U4/U8) inputs](https://github.com/SamiPerttu/fundsp/pull/51/commits/98dae088e389d77cccfb25c750d8537f32863369)

this cause a slight and expected performance drop:

» /usr/bin/time target/release/fundsp_player bank_simd dummy --seconds 400
        0.45 real         0.44 user         0.00 sys

**Comment by rhizoome** [comment]
@SamiPerttu I am currently thinking about how to implement `pub struct ResonatorBank` does it have U8 center and q inputs? Totalling to 24 inputs for f32x8?

**Comment by rhizoome** [comment]
In the thing I am building. I don't need a dynamic `ResonatorBanks`. I blend between two static `ResonatorBanks` as I found this sounds more natural than moving formants (even though the human voice produces moving formants). But I want to give a good interface to other users.

**Comment by rhizoome** [comment]
@SamiPerttu I finally looked into `response()` I think we could just use the same version as for `Biquad`, but adding an `index` parameter. But I still don't understand `fn route()`.

**Comment by SamiPerttu** [comment]
Interesting stats! Don't worry about routing, we can look at that later. Routing is like processing, except we're processing signals and not samples.

**Comment by rhizoome** [comment]
@SamiPerttu Thanks for merging. I just saw that I copy-pasted the `const ID: u64 = 15;`, that should probably become unique.

**Pull request merged**
