### PR TITLE
Non-generic `adsr_live()` and `adsr_fixed()`. Generic versions in `prelude.rs`.

### PR DESCRIPTION
**Pull request by gjf2a**
As suggested by @harudagondi in #17, I created non-generic versions of `adsr_live()` and `adsr_fixed()` and placed them in `hacker.rs` and `hacker32.rs`. I moved the generic versions to `prelude.rs`.

### CODE REVIEW

**Review by harudagondi — COMMENTED** [review]
You should run `cargo fmt`

**Comment by gjf2a** [comment]
I ran `cargo fmt` and it did not report anything.

**Comment by gjf2a** [comment]
Thanks @harudagondi. I'm running it now.

**Comment by harudagondi** [comment]
You accidentally added the `.idea` folder. You should undo your last commit

**Comment by gjf2a** [comment]
Yikes, sorry about that. I've removed `.idea`. Thanks for pointing it out!

**Review by harudagondi — APPROVED** [review]

**Pull request merged**
